[build]
  command = "npm run build -- --localize"
  publish = "dist/portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/es/home"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/*"
  to = "/en/home"
  status = 302
  force = false
  conditions = {Language = ["en"]}

# Client-side routing (SPA)
[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200